sudo: false
dist: trusty

language: python
python:
  - 3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - lcov
      - cmake
      - git
      - curl
      - binutils-2.26

before_script:
  - export PATH=/usr/lib/binutils-2.26/bin:${PATH}
  - python --version
  - pip install conan jinja2 gcovr pytest websocket-client
  - export CC=`which gcc-5`
  - export CXX=`which g++-5`
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add conan-community https://api.bintray.com/conan/conan-community/conan
  - ./fips set config linux-make-debug
  - ./fips gen

script:
  - python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN
  - ./fips make unit_test_coverage
  - ./fips make integration_tests
